services:
  backups:
    build: .
    env_file: .env
    volumes:
      - /data/ente-photos:/data/ente-photos
      - ente-cli-data:/cli-data
      - results:/srv/backups
    restart: unless-stopped

volumes:
  ente-cli-data: {}
  results: {}
